
  <footer>
	<div class="row">
	  <div class="watermitch"></div>
	</div>
	<div class="row">
	  <div class="small-12 columns">
		<span class="powered">Powered By:</span>
		<div class="featuredPowered">
		  <a href="https://www.reddit.com/r/answerable/"><div class="reddit logo"></div></a>
		</div>
		<div class="featuredPowered">
		  <a href="http://miguel-perez.github.io/smoothState.js/"><div class="smoothstate logo"></div></a>
		</div>
		<div class="float-right copyright">
		  Copyright &copy; 2016 Alex Sinnott<br>
		  <a href="http://twitter.com/sifex">@sifex</a>
		</div>
	  </div>
	</div>
  </footer>

	<script src="/bower_components/jquery/dist/jquery.js"></script>
	<script src="/bower_components/what-input/what-input.js"></script>
	<script src="/bower_components/foundation-sites/dist/foundation.js"></script>
	<script src="/js/min/app-min.js"></script>
	<script src="/js/jquery.smoothState.js"></script>

	<script>

		;(function ($) {
		    $('#main').smoothState();
		})(jQuery);

	</script>

  </body>
</html>
