<!doctype html>
<html class="no-js" lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Answerable</title>
	<link rel="stylesheet" href="/styles/ans_global.css">
	<link rel="stylesheet" href="/styles/animate.css">
	<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
	<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />

  </head>
  <body>
  <header>
	<div class="row">
	  <a href="/"><div class="logo"></div></a>
	</div>
	<nav class="text-center">
	  <div class="row">
		<a id="faq" class="button secondary hollow" href="#FAQ">FAQ</a>
		<a id="submit" class="button" href="https://www.reddit.com/r/answerable/submit?selftext=true">Submit Issue</a>
		<a id="contact" class="button hollow secondary" href="#contact">Contact</a>
	  </div>
	</nav>
  </header>